on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        runner: [macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: build
          key: ${{ runner.os }}-cmake-build

      - run: |
          cmake -B build

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: build
          key: ${{ runner.os }}-cmake-build

      - run: |
          echo '## Debug' >> $GITHUB_STEP_SUMMARY
          cmake --build build --config Debug
          cmake --install build --config Debug --prefix install-debug
          ./install-debug/fourier-benchmarking >> $GITHUB_STEP_SUMMARY

          echo '# Release' >> $GITHUB_STEP_SUMMARY
          cmake --build build --config Release
          cmake --install build --config Release --prefix install-release
          ./install-release/fourier-benchmarking >> $GITHUB_STEP_SUMMARY
